# Copyright (c) 0x5BFA
# Licensed under the MIT License. See the LICENSE.

name: JumpListManager CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/assets/**'
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - '.github/assets/**'
      - 'docs/**'
      - '*.md'

run-name: ${{ github.event_name == 'pull_request' && 'JumpListManager PR Validation' || 'JumpListManager CI Validation' }}

env:
  WORKING_DIR:           '${{ github.workspace }}' # 'D:\a\JumpListManager\JumpListManager'
  SOLUTION_PATH:         '${{ github.workspace }}\JumpListManager.slnx'
  WASDK_PROJ_PATH:       '${{ github.workspace }}\JumpListManager.Samples.WinUI\JumpListManager.Samples.WinUI.csproj'
  UWP_PROJ_PATH:         '${{ github.workspace }}\JumpListManager.Samples.Uwp\JumpListManager.Samples.Uwp.csproj'

jobs:
  build-wasdk:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        platform: [x64, ARM64]
    env:
      CONFIGURATION: ${{ matrix.configuration }}
      PLATFORM: ${{ matrix.platform }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Build the WASDK sample
      run: msbuild /restore $env:ENTRYPOINT_PROJ_PATH /p:Configuration=$env:CONFIGURATION /p:Platform=$env:PLATFORM /p:AppxBundle=Never

  build-uwp:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        platform: [x64, ARM64]
    env:
      CONFIGURATION: ${{ matrix.configuration }}
      PLATFORM: ${{ matrix.platform }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Build the sample
      run: msbuild /restore $env:UWP_PROJ_PATH /p:Configuration=$env:CONFIGURATION /p:Platform=$env:PLATFORM /p:AppxBundle=Never
